"""add_eisenhower_and_frog_fields

Revision ID: 293cd8c1b192
Revises: dda42c8c9d3e
Create Date: 2026-04-23 12:17:57.625509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293cd8c1b192'
down_revision: Union[str, Sequence[str], None] = 'dda42c8c9d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Integer(), nullable=False, server_default='2'))
        batch_op.add_column(sa.Column('urgency', sa.Integer(), nullable=False, server_default='2'))
        batch_op.add_column(sa.Column('is_frog', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_frog')
        batch_op.drop_column('urgency')
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
