"""many_to_many_interactions

Revision ID: 43d4a1ecc20b
Revises: 458ae274e046
Create Date: 2026-04-22 07:24:13.087862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d4a1ecc20b'
down_revision: Union[str, Sequence[str], None] = '458ae274e046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholderinteractionlink',
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['stakeholderinteraction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id', 'stakeholder_id')
    )
    with op.batch_alter_table('stakeholderinteraction', schema=None) as batch_op:
        batch_op.drop_column('stakeholder_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholderinteraction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stakeholder_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(None, 'stakeholder', ['stakeholder_id'], ['id'], ondelete='CASCADE')

    op.drop_table('stakeholderinteractionlink')
    # ### end Alembic commands ###
