"""add_stakeholder_interaction

Revision ID: 458ae274e046
Revises: 69e230c2e0f6
Create Date: 2026-04-22 07:16:11.629721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '458ae274e046'
down_revision: Union[str, Sequence[str], None] = '69e230c2e0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholderinteraction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'tense', 'hostile', name='sentimentenum'), nullable=False),
    sa.Column('lesson_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('advice_received', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stakeholderinteraction')
    # ### end Alembic commands ###
