"""add_personal_mirror_models

Revision ID: 4b6e7643ed9b
Revises: c2a2a50781c6
Create Date: 2026-04-23 09:21:01.599128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b6e7643ed9b'
down_revision: Union[str, Sequence[str], None] = 'c2a2a50781c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaltrait',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('strength', 'weakness', name='traitcategory'), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personaltrait', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personaltrait_name'), ['name'], unique=False)

    op.create_table('reflectionaudit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trait_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trait_id'], ['personaltrait.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reflectionaudit')
    with op.batch_alter_table('personaltrait', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personaltrait_name'))

    op.drop_table('personaltrait')
    # ### end Alembic commands ###
