"""add_project_trait_link

Revision ID: 5506096b2847
Revises: 90ba1c10da50
Create Date: 2026-04-23 12:06:35.053665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5506096b2847'
down_revision: Union[str, Sequence[str], None] = '90ba1c10da50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projecttraitlink',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('trait_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['personaltrait.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'trait_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projecttraitlink')
    # ### end Alembic commands ###
