"""add_project_stakeholder_link

Revision ID: 680037e10296
Revises: f983a9cd0332
Create Date: 2026-04-22 21:49:10.161432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680037e10296'
down_revision: Union[str, Sequence[str], None] = 'f983a9cd0332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectstakeholderlink',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'stakeholder_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectstakeholderlink')
    # ### end Alembic commands ###
