"""add_trait_type

Revision ID: 90ba1c10da50
Revises: cd6ac4fd04c0
Create Date: 2026-04-23 10:00:07.804038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ba1c10da50'
down_revision: Union[str, Sequence[str], None] = 'cd6ac4fd04c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaltrait', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trait_type', sa.Enum('general', 'technical', name='traittype'), nullable=False, server_default='general'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaltrait', schema=None) as batch_op:
        batch_op.drop_column('trait_type')

    # ### end Alembic commands ###
