"""add_use_second_api_key_to_settings

Revision ID: b94b32b29ee5
Revises: 293cd8c1b192
Create Date: 2026-04-23 14:54:33.725602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94b32b29ee5'
down_revision: Union[str, Sequence[str], None] = '293cd8c1b192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ossettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_second_api_key', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ossettings', schema=None) as batch_op:
        batch_op.drop_column('use_second_api_key')

    # ### end Alembic commands ###
