"""link_project_to_organization

Revision ID: c2a2a50781c6
Revises: 680037e10296
Create Date: 2026-04-22 22:00:55.346331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a2a50781c6'
down_revision: Union[str, Sequence[str], None] = '680037e10296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_project_organization', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_organization', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
