"""add_strategic_quotas_and_principles

Revision ID: e89ae22ea536
Revises: 37f0c3f4a95e
Create Date: 2026-04-20 12:59:22.720463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e89ae22ea536'
down_revision: Union[str, Sequence[str], None] = '37f0c3f4a95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidingprinciple',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actionable_advice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategicgoal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_days_per_week', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('slot_duration_minutes', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('min_weekly_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_weekly_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategicgoal', schema=None) as batch_op:
        batch_op.drop_column('max_weekly_hours')
        batch_op.drop_column('min_weekly_hours')
        batch_op.drop_column('slot_duration_minutes')
        batch_op.drop_column('min_days_per_week')

    op.drop_table('guidingprinciple')
    # ### end Alembic commands ###
