"""add_stakeholder_circle

Revision ID: f983a9cd0332
Revises: eb55666ba8ef
Create Date: 2026-04-22 21:26:44.591738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f983a9cd0332'
down_revision: Union[str, Sequence[str], None] = 'eb55666ba8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circle', sa.Enum('teammate', 'client', 'same_org', 'different_org', name='circleenum'), nullable=False, server_default='same_org'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder', schema=None) as batch_op:
        batch_op.drop_column('circle')

    # ### end Alembic commands ###
